import { NextRequest, NextResponse } from 'next/server'
import { connectDB } from '@/lib/mongodb'
import { MenuItem } from '@/models/MenuItem'
import { Order } from '@/models/Order'

const MENU_SEED = [
  // ── Plats ──────────────────────────────────────────────
  {
    name: 'Taro / Achu',
    description: 'Plat traditionnel camerounais à base de taro pilé, servi avec sauce viande.',
    price: 18,
    category: 'Plats',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650557/Achu_r7lium.png',
    available: true,
  },
  {
    name: 'Eru',
    description: 'Feuilles d\'eru mijotées avec waterleaf, huile de palme et viande fumée.',
    price: 15,
    category: 'Plats',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650557/eru_nolnxb.png',
    available: true,
  },
  {
    name: 'Ndolé',
    description: 'Feuilles de ndolé aux arachides, crevettes et viande. Plat national camerounais.',
    price: 15,
    category: 'Plats',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650558/ndol%C3%A9_wqahkd.png',
    available: true,
  },
  {
    name: 'Ngombo',
    description: 'Sauce gombo à base d\'okra, poisson fumé et épices africaines.',
    price: 15,
    category: 'Plats',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650558/gombo_rxne5l.png',
    available: true,
  },
  {
    name: 'Egussi',
    description: 'Soupe d\'egussi aux graines de courge, légumes et viande.',
    price: 15,
    category: 'Plats',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777829576/Screenshot_2026-05-03_at_19.32.27_hue0lj.png',
    available: true,
  },
  {
    name: 'Ailes de poulet',
    description: 'Ailes de poulet marinées et grillées, accompagnées de sauce piquante.',
    price: 10,
    category: 'Plats',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777652100/ailles_fqb4xi.png',
    available: true,
  },
  // ── Braise ─────────────────────────────────────────────
  {
    name: 'Poisson Bar',
    description: 'Bar entier grillé au charbon, servi avec sauce tomate et plantain.',
    price: 15,
    category: 'Braise',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650557/fish2_igp3mq.png',
    available: true,
  },
  {
    name: 'Tilapia braisé',
    description: 'Tilapia grillé, mariné aux épices africaines. Petit 12€ / Grand 15€.',
    price: 12,
    category: 'Braise',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650558/fish_cvn5i0.png',
    available: true,
  },
  {
    name: 'Chinchard',
    description: 'Chinchard braisé au feu de bois, servi avec sauce pimentée.',
    price: 15,
    category: 'Braise',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777652100/chinchard_da2iwt.png',
    available: true,
  },
  {
    name: 'Maquereau braisé',
    description: 'Maquereau entier grillé, parfumé aux herbes et citron.',
    price: 15,
    category: 'Braise',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777652100/makereau_rkfpcs.png',
    available: true,
  },
  {
    name: 'Brochette',
    description: 'Brochettes de viande marinée grillées au charbon.',
    price: 10,
    category: 'Braise',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650558/brochettes_tcgb7e.png',
    available: true,
  },
  {
    name: 'Porc braisé',
    description: 'Morceaux de porc marinés et grillés, servis avec sauce piquante.',
    price: 12,
    category: 'Braise',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777893938/porc_f5zsaa.png',
    available: true,
  },
  // ── Accompagnements ────────────────────────────────────
  {
    name: 'Riz',
    description: 'Riz blanc cuit à la vapeur.',
    price: 3,
    category: 'Accompagnements',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777894460/riz1_ejwlzm.png',
    available: true,
  },
  {
    name: 'Plantain bouilli',
    description: 'Plantain mûr cuit à l\'eau.',
    price: 3,
    category: 'Accompagnements',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650558/plantain_lxsivx.png',
    available: true,
  },
  {
    name: 'Plantain Tapé',
    description: 'Plantain grillé au charbon, légèrement caramélisé.',
    price: 3,
    category: 'Accompagnements',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650558/Tap%C3%A9_uyrihg.png',
    available: true,
  },
  {
    name: 'Bananes frites',
    description: 'Tranches de plantain frites, dorées et croustillantes.',
    price: 3,
    category: 'Accompagnements',
    image: 'https://images.unsplash.com/photo-1563336522-c3bd728d3b45?w=400',
    available: true,
  },
  {
    name: 'Semoule',
    description: 'Semoule de maïs ou blé, épaisse et onctueuse.',
    price: 3,
    category: 'Accompagnements',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650558/s%C3%A9moule_x436ti.png',
    available: true,
  },
  {
    name: 'Garri',
    description: 'Farine de manioc fermenté, accompagnement traditionnel ouest-africain.',
    price: 3,
    category: 'Accompagnements',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650557/garri_ubcuus.png',
    available: true,
  },
  {
    name: 'Manioc / Bobolo',
    description: 'Manioc fermenté et cuit en feuille de bananier (Bobolo).',
    price: 3,
    category: 'Accompagnements',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777650558/miondo_hwmsxa.png',
    available: true,
  },
  // ── Boissons ───────────────────────────────────────────
  {
    name: 'Coca Cola',
    description: 'Coca Cola bien frais. 33cl 3€ / 1L 6€.',
    price: 3,
    category: 'Boissons',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
    available: true,
  },
  {
    name: 'Fanta',
    description: 'Fanta orange glacé. 33cl 3€ / 1L 6€.',
    price: 3,
    category: 'Boissons',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777828922/Screenshot_2026-05-03_at_19.19.50_epjkok.png',
    available: true,
  },
  {
    name: 'TOPs',
    description: 'Soda pétillant au pamplemousse.',
    price: 6,
    category: 'Boissons',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656884/top_zbrfjr.png',
    available: true,
  },
  {
    name: "D'jino Cocktail",
    description: 'Boisson fruitée D\'jino cocktail.',
    price: 6,
    category: 'Boissons',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656884/Djino_ewp8fn.png',
    available: true,
  },
  // ── Bières ─────────────────────────────────────────────
  {
    name: 'Heineken',
    description: 'Heineken 33cl bien fraîche.',
    price: 5,
    category: 'Bières',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656885/HEINEKEN_mhnbvm.png',
    available: true,
  },
  {
    name: '1664',
    description: 'Kronenbourg 1664 33cl.',
    price: 5.50,
    category: 'Bières',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656883/1664_ktisrc.png',
    available: true,
  },
  {
    name: 'Mützig',
    description: 'Bière africaine Mützig, bouteille.',
    price: 10,
    category: 'Bières',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656884/mutzig_nprqxa.png',
    available: true,
  },
  {
    name: 'Booster',
    description: 'Bière Booster, bouteille.',
    price: 10,
    category: 'Bières',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656884/BOOSTER_tylwj9.png',
    available: true,
  },
  {
    name: '33 Export',
    description: 'Bière 33 Export, bouteille.',
    price: 10,
    category: 'Bières',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656977/33_vdjynu.png',
    available: true,
  },
  {
    name: 'Guinness',
    description: 'Guinness stout. Canette 5€ / Bouteille 10€.',
    price: 5,
    category: 'Bières',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656884/gUINESS_h93agn.png',
    available: true,
  },
  // ── Vins ───────────────────────────────────────────────
  {
    name: 'Vin Rouge',
    description: 'Vins rouges sélectionnés. Verre 15€ / Bouteille 20€.',
    price: 15,
    category: 'Vins',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656883/vin_rouge_depzkp.png',
    available: true,
  },
  {
    name: 'Vin Blanc',
    description: 'Vins blancs sélectionnés. Verre 15€ / Bouteille 20€.',
    price: 15,
    category: 'Vins',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656883/vin_blanc_uzfkgt.png',
    available: true,
  },
  // ── Champagnes ─────────────────────────────────────────
  {
    name: 'Moët & Chandon',
    description: 'Champagne Moët & Chandon, bouteille.',
    price: 80,
    category: 'Champagnes',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656883/Moet_wvkjlf.png',
    available: true,
  },
  {
    name: 'Veuve Clicquot',
    description: 'Champagne Veuve Clicquot, bouteille.',
    price: 90,
    category: 'Champagnes',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656884/veuve_pzbe1k.png',
    available: true,
  },
  {
    name: 'Ruinart',
    description: 'Champagne Ruinart, bouteille.',
    price: 150,
    category: 'Champagnes',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656883/ruinart_xlvfpd.png',
    available: true,
  },
  {
    name: 'Mumm',
    description: 'Champagne G.H. Mumm, bouteille.',
    price: 80,
    category: 'Champagnes',
    image: 'https://res.cloudinary.com/dkd3k6eau/image/upload/v1777656883/MUMM_jhj2gp.png',
    available: true,
  },
]

export async function POST(_req: NextRequest) {
  if (process.env.NODE_ENV !== 'development') {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }
  await connectDB()
  await MenuItem.deleteMany({})
  await Order.deleteMany({})
  const items = await MenuItem.insertMany(MENU_SEED)
  return NextResponse.json({ message: 'Database seeded', count: items.length })
}
